security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ACHETEUR: ROLE_USER
        ROLE_VENDEUR: ROLE_USER
        ROLE_MODERATEUR: [ROLE_ACHETEUR, ROLE_VENDEUR]
        ROLE_ADMIN: ROLE_MODERATEUR
      #le role user coté gauche on ne le met jamais

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # csrf_token, c'est une chaine de charactere que je donne en model unique par securité
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back-office/, role: ROLE_ADMIN }
        #si la redirection comporte une erreur dans le role de la personne qui demande l'acces, une erreur s'affiche
        #en gros c'est le controle des routes et la redirection si necessaire
